// src/constants/mentors.seed.ts
import { PROFESSION_DOMAINS } from './professionalDomain';

export const mentorsData = [
  // SOFTWARE_ENGINEERING (3 জন)
  {
    email: "tahmid.rahman@example.com",
    name: "Tahmid Rahman",
    profileURL: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    headline: "Lead Architect & Cloud Consultant",
    bio: "10+ years architecting fault-tolerant cloud infrastructures on AWS and GCP. Mentoring software engineers targeting senior and staff-level transitions.",
    yearOfExperience: 10,
    expertiseTags: ["AWS", "System Design", "Microservices", "Docker", "Kubernetes"],
    linkedinURL: "https://www.linkedin.com/in/tahmid-rahman",
    professionalDomain: PROFESSION_DOMAINS.SOFTWARE_ENGINEERING,
    sessionCharge: 50.0,
    averageRatings: 4.95,
    totalReviews: 42,
  },
  {
    email: "sarah.alvi@example.com",
    name: "Sarah Alvi",
    profileURL: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    headline: "Staff Software Engineer @ FinTech",
    bio: "Passionate about high-throughput distributed systems, event-driven architectures, and Go/Rust microservices. Helping folks ace technical coding interviews.",
    yearOfExperience: 8,
    expertiseTags: ["Golang", "Distributed Systems", "Kafka", "PostgreSQL", "Algorithms"],
    linkedinURL: "https://www.linkedin.com/in/sarah-alvi",
    professionalDomain: PROFESSION_DOMAINS.SOFTWARE_ENGINEERING,
    sessionCharge: 45.0,
    averageRatings: 4.88,
    totalReviews: 36,
  },
  {
    email: "asif.chowdhury@example.com",
    name: "Asif Chowdhury",
    profileURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    headline: "Principal Full Stack Engineer",
    bio: "Full stack ecosystem enthusiast with deep expertise in Next.js, TypeScript, and Node.js. Guiding engineers on frontend architecture and scalable backend integration.",
    yearOfExperience: 9,
    expertiseTags: ["Next.js", "React", "TypeScript", "Node.js", "GraphQL"],
    linkedinURL: "https://www.linkedin.com/in/asif-chowdhury",
    professionalDomain: PROFESSION_DOMAINS.SOFTWARE_ENGINEERING,
    sessionCharge: 40.0,
    averageRatings: 4.92,
    totalReviews: 29,
  },

  // DATA_SCIENCE_AND_AI (3 জন)
  {
    email: "tanvir.hasan@example.com",
    name: "Dr. Tanvir Hasan",
    profileURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    headline: "AI Research Scientist & LLM Specialist",
    bio: "PhD in Machine Learning. Guiding researchers and practitioners on Transformer architectures, generative AI deployment, and predictive modeling with PyTorch.",
    yearOfExperience: 7,
    expertiseTags: ["PyTorch", "LLMs", "Transformers", "NLP", "MLOps"],
    linkedinURL: "https://www.linkedin.com/in/tanvir-hasan",
    professionalDomain: PROFESSION_DOMAINS.DATA_SCIENCE_AND_AI,
    sessionCharge: 55.0,
    averageRatings: 4.96,
    totalReviews: 38,
  },
  {
    email: "nawshin.tabassum@example.com",
    name: "Nawshin Tabassum",
    profileURL: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    headline: "Senior Data Scientist @ HealthTech",
    bio: "Specialized in clinical data analysis, predictive healthcare algorithms, and tabular ML modeling (XGBoost, LightGBM, CatBoost).",
    yearOfExperience: 6,
    expertiseTags: ["Scikit-Learn", "XGBoost", "Python", "Predictive Modeling", "Pandas"],
    linkedinURL: "https://www.linkedin.com/in/nawshin-tabassum",
    professionalDomain: PROFESSION_DOMAINS.DATA_SCIENCE_AND_AI,
    sessionCharge: 42.0,
    averageRatings: 4.89,
    totalReviews: 27,
  },
  {
    email: "farhan.ishraq@example.com",
    name: "Farhan Ishraq",
    profileURL: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    headline: "MLOps Engineer & Big Data Strategist",
    bio: "Bridging the gap between raw data science pipelines and reliable cloud production. Mentoring on automated retraining pipelines, MLflow, and Kubeflow.",
    yearOfExperience: 5,
    expertiseTags: ["MLOps", "Kubeflow", "Docker", "Python", "Data Pipelines"],
    linkedinURL: "https://www.linkedin.com/in/farhan-ishraq",
    professionalDomain: PROFESSION_DOMAINS.DATA_SCIENCE_AND_AI,
    sessionCharge: 38.0,
    averageRatings: 4.82,
    totalReviews: 19,
  },

  // UI_UX_DESIGN (2 জন)
  {
    email: "sumaiya.zaman@example.com",
    name: "Sumaiya Zaman",
    profileURL: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
    headline: "Product Design Lead & Design Systems Specialist",
    bio: "Helping designers craft scalable enterprise design systems and build high-conversion UX flows. Portfolio reviews and interview strategy sessions.",
    yearOfExperience: 8,
    expertiseTags: ["Figma", "Design Systems", "User Research", "Interaction Design", "Prototyping"],
    linkedinURL: "https://www.linkedin.com/in/sumaiya-zaman",
    professionalDomain: PROFESSION_DOMAINS.UI_UX_DESIGN,
    sessionCharge: 35.0,
    averageRatings: 4.97,
    totalReviews: 51,
  },
  {
    email: "rayhan.kabir@example.com",
    name: "Rayhan Kabir",
    profileURL: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    headline: "Senior UX Strategist @ Global Agency",
    bio: "Specialized in user usability testing, heuristic evaluation, and wireframing for complex SaaS products. Transition guidance for junior designers.",
    yearOfExperience: 6,
    expertiseTags: ["UX Strategy", "Figma", "Wireframing", "Information Architecture"],
    linkedinURL: "https://www.linkedin.com/in/rayhan-kabir",
    professionalDomain: PROFESSION_DOMAINS.UI_UX_DESIGN,
    sessionCharge: 30.0,
    averageRatings: 4.85,
    totalReviews: 24,
  },

  // PRODUCT_MANAGEMENT (2 জন)
  {
    email: "kamrul.islam@example.com",
    name: "Kamrul Islam",
    profileURL: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80",
    headline: "Group Product Manager @ Enterprise SaaS",
    bio: "Guiding aspiring and associate PMs on product roadmapping, discovery frameworks, stakeholder alignment, and product metrics optimization.",
    yearOfExperience: 9,
    expertiseTags: ["Product Strategy", "Roadmapping", "Agile", "User Stories", "KPI Metrics"],
    linkedinURL: "https://www.linkedin.com/in/kamrul-islam",
    professionalDomain: PROFESSION_DOMAINS.PRODUCT_MANAGEMENT,
    sessionCharge: 48.0,
    averageRatings: 4.91,
    totalReviews: 33,
  },
  {
    email: "mehnaz.perveen@example.com",
    name: "Mehnaz Perveen",
    profileURL: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=400&q=80",
    headline: "Senior Technical Product Manager",
    bio: "Ex-engineer turned PM. Helping professionals bridge engineering execution with business value, OKR planning, and product-market fit validation.",
    yearOfExperience: 7,
    expertiseTags: ["Tech PM", "Product Growth", "Data-Driven Discovery", "Scrum"],
    linkedinURL: "https://www.linkedin.com/in/mehnaz-perveen",
    professionalDomain: PROFESSION_DOMAINS.PRODUCT_MANAGEMENT,
    sessionCharge: 40.0,
    averageRatings: 4.87,
    totalReviews: 22,
  },

  // DEVOPS_AND_CLOUD_COMPUTING (2 জন)
  {
    email: "sabbir.ahmed@example.com",
    name: "Sabbir Ahmed",
    profileURL: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80",
    headline: "Lead Site Reliability Engineer",
    bio: "Specializing in zero-downtime deployments, Kubernetes cluster scaling, Terraform IaC, and robust observability pipelines using Prometheus and Grafana.",
    yearOfExperience: 8,
    expertiseTags: ["Kubernetes", "Terraform", "CI/CD", "AWS", "Grafana"],
    linkedinURL: "https://www.linkedin.com/in/sabbir-ahmed",
    professionalDomain: PROFESSION_DOMAINS.DEVOPS_AND_CLOUD_COMPUTING,
    sessionCharge: 45.0,
    averageRatings: 4.93,
    totalReviews: 31,
  },
  {
    email: "shakil.mahmud@example.com",
    name: "Shakil Mahmud",
    profileURL: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    headline: "Cloud Solutions Architect",
    bio: "Architecting hybrid multi-cloud infrastructure and automated GitHub Actions workflows. Preparing engineers for AWS Certified Solutions Architect exams.",
    yearOfExperience: 6,
    expertiseTags: ["Cloud Architecture", "GitHub Actions", "Docker", "Linux", "GCP"],
    linkedinURL: "https://www.linkedin.com/in/shakil-mahmud",
    professionalDomain: PROFESSION_DOMAINS.DEVOPS_AND_CLOUD_COMPUTING,
    sessionCharge: 38.0,
    averageRatings: 4.86,
    totalReviews: 20,
  },

  // CYBERSECURITY (2 জন)
  {
    email: "arefin.shuvo@example.com",
    name: "Arefin Shuvo",
    profileURL: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    headline: "Principal Application Security Engineer",
    bio: "Offensive security specialist, penetration tester, and bug bounty hunter. Assisting developers in securing APIs, web vulnerabilities, and OWASP top 10 flaws.",
    yearOfExperience: 7,
    expertiseTags: ["AppSec", "Penetration Testing", "OWASP", "Vulnerability Management"],
    linkedinURL: "https://www.linkedin.com/in/arefin-shuvo",
    professionalDomain: PROFESSION_DOMAINS.CYBERSECURITY,
    sessionCharge: 45.0,
    averageRatings: 4.94,
    totalReviews: 28,
  },
  {
    email: "tasnim.jahan@example.com",
    name: "Tasnim Jahan",
    profileURL: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    headline: "Information Security Consultant & Auditor",
    bio: "Focusing on enterprise SOC readiness, compliance frameworks (ISO 27001, SOC 2), and security architecture review sessions.",
    yearOfExperience: 6,
    expertiseTags: ["SOC 2", "Compliance", "Network Security", "Risk Assessment"],
    linkedinURL: "https://www.linkedin.com/in/tasnim-jahan",
    professionalDomain: PROFESSION_DOMAINS.CYBERSECURITY,
    sessionCharge: 35.0,
    averageRatings: 4.88,
    totalReviews: 17,
  },

  // CAREER_AND_JOB_SEARCH (2 জন)
  {
    email: "mahmudul.haque@example.com",
    name: "Mahmudul Haque",
    profileURL: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&q=80",
    headline: "Senior Tech Talent Partner & Career Strategist",
    bio: "8+ years screening technical candidates. Providing mock behavioral interviews, resume audits, compensation negotiation tips, and global job search strategies.",
    yearOfExperience: 8,
    expertiseTags: ["Resume Audit", "Mock Interviews", "Salary Negotiation", "Tech Hiring"],
    linkedinURL: "https://www.linkedin.com/in/mahmudul-haque",
    professionalDomain: PROFESSION_DOMAINS.CAREER_AND_JOB_SEARCH,
    sessionCharge: 32.0,
    averageRatings: 4.98,
    totalReviews: 64,
  },
  {
    email: "nadia.sultana@example.com",
    name: "Nadia Sultana",
    profileURL: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?auto=format&fit=crop&w=400&q=80",
    headline: "Career Transformation Coach",
    bio: "Helping non-tech professionals transition smoothly into tech tracks. Actionable personalized roadmaps, LinkedIn presence optimization, and cold outreach coaching.",
    yearOfExperience: 5,
    expertiseTags: ["Career Transition", "LinkedIn Optimization", "Interview Prep"],
    linkedinURL: "https://www.linkedin.com/in/nadia-sultana",
    professionalDomain: PROFESSION_DOMAINS.CAREER_AND_JOB_SEARCH,
    sessionCharge: 28.0,
    averageRatings: 4.9,
    totalReviews: 45,
  },

  // BUSINESS_AND_STARTUPS (2 জন)
  {
    email: "zahed.chowdhury@example.com",
    name: "Zahed Chowdhury",
    profileURL: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    headline: "Startup Founder & Angel Investor",
    bio: "Scaled two tech startups from seed to Series A. Mentoring early-stage founders on pitch decks, customer discovery, unit economics, and venture fundraising.",
    yearOfExperience: 11,
    expertiseTags: ["Fundraising", "Pitch Decks", "Business Modeling", "Go-To-Market"],
    linkedinURL: "https://www.linkedin.com/in/zahed-chowdhury",
    professionalDomain: PROFESSION_DOMAINS.BUSINESS_AND_STARTUPS,
    sessionCharge: 60.0,
    averageRatings: 4.97,
    totalReviews: 41,
  },
  {
    email: "samira.anjum@example.com",
    name: "Samira Anjum",
    profileURL: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    headline: "Operations & Growth Strategist",
    bio: "Ex-operations director guiding founders on sustainable burn rates, operational scaling, and cross-functional team productivity.",
    yearOfExperience: 7,
    expertiseTags: ["Operations", "Strategic Planning", "B2B Sales", "Team Scaling"],
    linkedinURL: "https://www.linkedin.com/in/samira-anjum",
    professionalDomain: PROFESSION_DOMAINS.BUSINESS_AND_STARTUPS,
    sessionCharge: 45.0,
    averageRatings: 4.89,
    totalReviews: 23,
  },

  // DIGITAL_MARKETING (2 জন)
  {
    email: "rifat.khandaker@example.com",
    name: "Rifat Khandaker",
    profileURL: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=400&q=80",
    headline: "Performance Marketing & Growth Lead",
    bio: "Scaled advertising campaigns generating $5M+ in revenue across Google, Meta, and LinkedIn. Advising on attribution models, CAC reduction, and SEO strategies.",
    yearOfExperience: 7,
    expertiseTags: ["Performance Marketing", "Meta Ads", "SEO", "Growth Hacking"],
    linkedinURL: "https://www.linkedin.com/in/rifat-khandaker",
    professionalDomain: PROFESSION_DOMAINS.DIGITAL_MARKETING,
    sessionCharge: 35.0,
    averageRatings: 4.88,
    totalReviews: 30,
  },
  {
    email: "anika.bushra@example.com",
    name: "Anika Bushra",
    profileURL: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80",
    headline: "Brand Marketing & Content Strategist",
    bio: "Helping B2B brands and personal brands craft compelling organic narratives, inbound marketing funnels, and viral thought leadership content.",
    yearOfExperience: 6,
    expertiseTags: ["Content Marketing", "Brand Strategy", "Social Media Funnels", "Copywriting"],
    linkedinURL: "https://www.linkedin.com/in/anika-bushra",
    professionalDomain: PROFESSION_DOMAINS.DIGITAL_MARKETING,
    sessionCharge: 30.0,
    averageRatings: 4.92,
    totalReviews: 26,
  },
];